// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5536.Titan2016;

import org.usfirst.frc5536.Titan2016.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;

import org.usfirst.frc5536.Titan2016.subsystems.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton joystickButton7;
    public Joystick leftJoystick;
    public JoystickButton joystickButton8;
    public Joystick rightJoystick;
    public JoystickButton joystickButton1;
    public JoystickButton joystickButton2;
    public JoystickButton joystickButton3;
    public JoystickButton joystickButton4;
    public JoystickButton joystickButton5;
    public JoystickButton joystickButton6;
    public JoystickButton joystickButton9;
    public Joystick xbox;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        xbox = new Joystick(2);
        
        joystickButton9 = new JoystickButton(xbox, 9);
        joystickButton9.whenPressed(new AutoFire());
        joystickButton6 = new JoystickButton(xbox, 6);
        joystickButton6.whileHeld(new armUp());
        joystickButton5 = new JoystickButton(xbox, 5);
        joystickButton5.whileHeld(new armDown());
        joystickButton4 = new JoystickButton(xbox, 4);
        joystickButton4.whileHeld(new intakeRev());
        joystickButton3 = new JoystickButton(xbox, 3);
        joystickButton3.whileHeld(new intakeFwd());
        joystickButton2 = new JoystickButton(xbox, 2);
        joystickButton2.whileHeld(new shooterRev());
        joystickButton1 = new JoystickButton(xbox, 1);
        joystickButton1.whileHeld(new shooterFwd());
        rightJoystick = new Joystick(1);
        
        joystickButton8 = new JoystickButton(rightJoystick, 1);
        joystickButton8.whileHeld(new strongArmUp());
        leftJoystick = new Joystick(0);
        
        joystickButton7 = new JoystickButton(leftJoystick, 1);
        joystickButton7.whileHeld(new strongArmDown());


        // SmartDashboard Buttons
        SmartDashboard.putData("intakeRev", new intakeRev());
        SmartDashboard.putData("intakeFwd", new intakeFwd());
        SmartDashboard.putData("driveWithJoystick", new driveWithJoystick());
        SmartDashboard.putData("shooterFwd", new shooterFwd());
        SmartDashboard.putData("shooterRev", new shooterRev());
        SmartDashboard.putData("armUp", new armUp());
        SmartDashboard.putData("armDown", new armDown());
        SmartDashboard.putData("fire", new fire());
        SmartDashboard.putData("armShooter", new armShooter());
        SmartDashboard.putData("armUpAuto", new armUpAuto());
        SmartDashboard.putData("turnRight45", new turnRight45());
        SmartDashboard.putData("shooterFwdAuto", new shooterFwdAuto());
        SmartDashboard.putData("AutoFire", new AutoFire());
        SmartDashboard.putData("Autonomous1", new Autonomous1());
        SmartDashboard.putData("driveFwdAuto", new driveFwdAuto());
        SmartDashboard.putData("fwdToPosistionAuto1", new fwdToPosistionAuto1());
        SmartDashboard.putData("Autonomous2", new Autonomous2());
        SmartDashboard.putData("turnRight90", new turnRight90());
        SmartDashboard.putData("fwdToPositionAuto2", new fwdToPositionAuto2());
        SmartDashboard.putData("turnLeft45", new turnLeft45());
        SmartDashboard.putData("turnLeft90", new turnLeft90());
        SmartDashboard.putData("highScoreDistance", new highScoreDistance());
        SmartDashboard.putData("wait", new wait());
        SmartDashboard.putData("strongArmUp", new strongArmUp());
        SmartDashboard.putData("strongArmDown", new strongArmDown());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getleftJoystick() {
        return leftJoystick;
    }

    public Joystick getrightJoystick() {
        return rightJoystick;
    }

    public Joystick getxbox() {
        return xbox;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

