// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5536.Titan2016.subsystems;

import org.usfirst.frc5536.Titan2016.RobotMap;
import org.usfirst.frc5536.Titan2016.commands.*;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.Solenoid;


/**
 *
 */
public class shooter extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon rightShooter = RobotMap.shooterrightShooter;
    private final CANTalon leftShooter = RobotMap.shooterleftShooter;
    private final Solenoid fireSolenoid = RobotMap.shooterfireSolenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new fire());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
        
        
    }
    
    public void shooterFwd() {
    	leftShooter.set(1);
    	rightShooter.set(1);
    }
    
    public void shooterRev() {
    	leftShooter.set(-.65);
    	rightShooter.set(-.65);
    }
    
    public void shooterStop(){
    	leftShooter.set(0);
    	rightShooter.set(0);
    }
    
    public void fireStop() {
    	fireSolenoid.set(false);
    }
    
    public void fire() {
    	fireSolenoid.set(true);
    }
    

}

